### PR TITLE
Add proper type to workerProxy

### LINKED ISSUE #1: Better typing for SyncClient.workerProxy
I believe the correct typing for this value is `Remote<T>` (with Remote being a type exported from Comlink) instead of any. This would allow for proper TypeScript support when calling methods on the workerProxy directly if they are not syncExposed.

### PR DESCRIPTION
**Pull request by winniederidder**
Fixes #1

### CODE REVIEW

**Comment by alexmojaki** [comment]
Is it possible to allow not casting or declaring a type? Can `T` be `any` by default or something?

**Comment by alexmojaki** [comment]
Thanks. Should I release this?

**Comment by winniederidder** [comment]
A release would be useful for me, yes. Thanks!

**Comment by alexmojaki** [comment]
Done.

**Pull request merged**
